# Generated by Django 4.2 on 2023-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baham', '0002_userprofile_remove_companion_user_ptr_delete_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='contract',
            name='maintenance_share',
            field=models.PositiveSmallIntegerField(help_text='Percentage of maintenance cost contribution.'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='type',
            field=models.CharField(choices=[('AUTO_RICKSHAW', 'Auto Rickshaw'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatch Back'), ('SUV', 'Sub-Urban Vehicle'), ('VAN', 'Van'), ('HIGH_ROOF', 'High Roof'), ('MOTORCYCLE', 'Moto cycle/Scooter')], help_text='Select the vehicle chassis type', max_length=50),
        ),
    ]
